== Assignment 7

Get the permission resource for the permission named 'loanApproved'
In this assignment we perform the REST request for getting a permission resource by name.
This will be used in Assignment 9 when a loan officer approves the loan document,

=== API 
==== Request
[source,http]
GET /permissions/?name=loanApproved HTTP/1.1
HOST: localhost:8080
authorization: bearer eyJh...
content-type: application/json

==== Response
[source,json]
{
    "name": "loanApproved",
    "description": "Loan Approved",
    "owner": "app_admin",
    "roles": [{
        "name": "loan_officer",
        "permits": ["annotate", "comment", "print", "change_location", "browse", "read"]
    }, {
        "name": "loan_applicant",
        "permits": ["browse", "read"]
    }],
    "users": [],
    "tenantId": "acme",
    "_links": {
        "self": {
            "href": "http://localhost:8080/permissions/92zAADo6WtveilzTCj1i8O"
        }
    },
    "id": "92zAADo6WtveilzTCj1i8O",
    "eTag": 0
}

=== Service
==== Assignment:
The following function is to be used to get a permission resource by name and return the response item. Right now it returns empty.
Details of the required implementation are in the function comments

Location: `src/services/object.service.js`
[source,javascript]
    /**
     * TODO Assignment
     * For the given acl name get the corresponding permissions resource
     *     using the name as a paramter when requesting for permissions in the system
     *
     * Use the /permissions REST api and query by name
     *      ?name=xxx
     * Return the resource as promised
     * @param aclname
     * @returns {*|Promise.<TResult>}
     */
    fetchPermission(aclname: string) {
      return this.$q.resolve({});
    }
